services:
  chat-service:
    build: ./chat-service
    container_name: chat-service
    ports:
      - "${GO_PORT}:8080"
    env_file:
      - .env
    depends_on:
      - mysql
    networks:
      - app-network
    volumes:
      - ./chat-service:/app         
      - /app/tmp

  mysql:
    image: mysql:9.4.0
    container_name: mysql
    restart: always
    env_file:
      - .env
    ports:
      - "${MYSQL_PORT}:3306"
    volumes:
      - ./db-data:/var/lib/mysql
    networks:
      - app-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: always
    ports:
      - "${PMA_PORT}:80"
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: ${MYSQL_ROOT_PASSWORD}  # Use root password
    depends_on:
      - mysql
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  db-data:
